stages:
  - build

build_to_harbor:
  stage: build
  tags:
    - linux    
    - docker
  image:
    # Use the Infineon Artifactory mirror instead of gcr.io
    name: artifactory.infineon.com/docker-remote/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    # Tell Kaniko to use the Infineon Proxy to reach Harbor
    http_proxy: http://proxy.infineon.com:8080
    https_proxy: http://proxy.infineon.com:8080
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "harbor.infineon.com/rafeli/procurement-workbench:latest"
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
  only:
    - main